
#CC = gcc
CFLAGS = -g -Wall

default: test

# To create the executable file count we need the object files
# countwords.o, counter.o, and scanner.o:
#
test:  
	$(CC) $(CFLAGS) -o test Xilinx_Readback_Verify.c

clean:
	rm test
